### ISSUE TITLE
Target Machine actively refuses connection

### ISSUE THREAD

**Issue by dnbr2002** [picadoh/mockserver-client-csharp#3]
So I was pretty excited to find a MockServer port for .NET that was in .NET standard.  This should be a great tool for .NET Core Integrative and Compliance testing.  But when I run this on my local machine I am getting

> Message: System.AggregateException : One or more errors occurred. (No connection could be made because the target machine actively refused it)
---- System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it
-------- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it

My code is pretty straight forward.  I don't think I"ve gone off the reservation here at all.   
```
  public class JwtTokenServerHelper
    {
        public static MockServerClient CreateMockJwtTokenServer(string rsaPublicKey)
        {
            JObject jsonPublicTokenKey = new JObject();
            jsonPublicTokenKey.Add("alg", "sha256WithRSA");
            jsonPublicTokenKey.Add("value", rsaPublicKey);

            MockServerClient msc = new MockServerClient("127.0.0.1", 1080);
            msc
                .When(
                Request()
                .WithMethod("GET")
                .WithPath("/oauth/token_key"),
                Times.Exactly(1))
                .Respond(
                Response()
                .WithStatusCode(200)
                .WithHeaders(
                    new Header("Content-Type", "application/json; charset=utf-8"))
                    .WithBody(jsonPublicTokenKey.ToString())
                    .WithDelay(TimeSpan.FromMilliseconds(20))
                    );

            return msc;
        }
    }
```

It instantiaties the MockServerClient but when it goes to use the object, it fails with that error.  Any thoughts on why I might be getting this? I've tried multiple machines.  Same problem.

**Comment by dnbr2002** [comment]
I ran an almost identical config using WireMockNet

```
        public static FluentMockServer CreateMockJwtTokenServer(string rsaPublicKey)
        {
            JObject jsonPublicTokenKey = new JObject
            {
                { "alg", "sha256WithRSA" },
                { "value", rsaPublicKey }
            };

            FluentMockServer srv = FluentMockServer.Start();
            srv
                .Given(
                Request.Create()
                .WithPath("/oauth/token_key")
                .UsingGet()
                )
                .RespondWith(
                    Response.Create()
                    .WithStatusCode(200)
                    .WithHeader("Content-Type", "application/json; charset=utf-8")
                    .WithBody(jsonPublicTokenKey.ToString())
                    .WithDelay(TimeSpan.FromMilliseconds(20))
                );

            return srv;


        }
```

This one worked fine.  Not complaining.  Just an fyi.  I think maybe you have a bug, idk

**Comment by Tohaker** [comment]
I've found the same bug. Here is my stacktrace:
```
at Task`1.GetResultCore(Boolean waitCompletionNotification)
    at MockServerClient.SendExpectation(Expectation expectation)
    at WirelessCommandTest.SetupMockServer() in WirelessCommandTest.cs line: 18
    at WirelessCommandTest.ReceiveSuccessfulStatusCheck() in WirelessCommandTest.cs line: 48
    at ----- Inner Stack Trace -----
    at ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    at ValueTask`1.get_Result()
    at HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at ValueTask`1.get_Result()
    at HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
    at ValueTask`1.get_Result()
    at HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
    at RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
    at AbstractClient`1.SendRequestAsync(HttpRequestMessage httpRequest)
    at ----- Inner Stack Trace -----
    at ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```
Which comes from this code:
```
mockServer = new MockServerClient("127.0.0.1", 8080);
            mockServer
                .When(Request()
                    .WithMethod("GET")
                    .WithPath("/"),
                    Times.Unlimited())
                .Respond(Response()
                    .WithStatusCode(200)
                    .WithHeaders(
                        new Header("Content-Type", "application/json")
                        )
                    .WithBody("{ \"status\": \"success\" }")
                    .WithDelay(TimeSpan.FromSeconds(1)
                    )
                );
```

**Comment by picadoh** [comment]
Unfortunately, I'm not being able to reproduce the issue.

**Specs:**
- OS: macOS Mojave 10.14.5
- SDK: dotnet 2.1.505
- MockServer version: 5.6.1
- MockServer .NET Client version: 1.0.1

Either with or without using containers, it was not possible to reproduce the same error. If trying with Docker, for the sake of isolation, one may use this:

**docker-compose.yml**

```
version: '3.7'

services:
  mockserver:
   image: jamesdbloom/mockserver
   ports:
   - 1080:1080

  testapp:
    build: .
    depends_on:
      - mockserver
```

**Dockerfile**

```
FROM microsoft/dotnet:sdk AS build-env

WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "mocktest.dll"]
```

**Connection line**

```
new MockServerClient("mockserver", 1080);
```

**Test**

```
docker-compose run testapp
curl http://localhost:1080
{ "status": "success" }
```
